In [1]:
import numpy as np

In [2]:
arr = np.array([2,4])
arr

array([2, 4])

In [3]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [4]:
np.ones((1,2),dtype=int)

array([[1, 1]])

In [5]:
arr = np.arange(5)
print(arr)
op = np.where(arr %3==1,22,arr)
print(op)

[0 1 2 3 4]
[ 0 22  2  3 22]


In [6]:
arr = np.arange(100)
print(arr)
arr.reshape(5, -1) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [7]:
np.repeat(1, 5)

array([1, 1, 1, 1, 1])

In [8]:
a = np.arange(20).reshape(2,-1)
np.concatenate([a, a], axis=0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [9]:
np.vstack([a, a])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [10]:
np.r_[a, a]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [11]:
np.hstack([a, a])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [12]:
b=np.array([1,2,3,4])
np.tile(b, 3)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [13]:
np.intersect1d(a,b)

array([1, 2, 3, 4])

In [14]:
c = np.array([0,1,3,5,7])
d= np.array([1,2,4,5,6])
np.setdiff1d(c,d)

array([0, 3, 7])

In [15]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Apex/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Apex/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Apex/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:

In [16]:
Z = np.zeros((4,5))
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
Z.size

20

In [18]:
Z.itemsize

8

In [19]:
nz = np.nonzero([1,2,0,0,3,0,4]) 
nz

(array([0, 1, 4, 6], dtype=int64),)

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
 np.random.random((3,3))

array([[0.04638633, 0.99859924, 0.28822278],
       [0.65431341, 0.67892381, 0.88394315],
       [0.22656403, 0.95794569, 0.62276883]])

In [22]:
a.min()

0

In [23]:
a.max()

19

In [24]:
f=np.ones((5,5))
f

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.pad(f, pad_width=1, constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [26]:
np.diag(1+np.arange(4))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [27]:
np.dtype("a")

dtype('S')

In [28]:
type(a)

numpy.ndarray

In [29]:
np.shape(a)

(2, 10)

In [30]:
np.ravel(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
np.unravel_index(2,(2,2))

(1, 0)

In [32]:
np.mean(a)

9.5

In [33]:
np.dot(5,4)

20

In [34]:
np.random.randint(0,10,10)

array([6, 8, 9, 0, 2, 2, 3, 0, 7, 3])

In [35]:
np.sqrt(25)

5.0

In [36]:
 np.datetime64('today')

numpy.datetime64('2020-12-30')

In [37]:
np.add(2,3)

5

In [38]:
np.divide(3,5)

0.6

In [39]:
np.negative(5)

-5

In [40]:
np.multiply(5,2)

10

In [41]:
np.floor(a)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.]])

In [42]:
np.trunc(a)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.]])

In [43]:
a.astype(str)

array([['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
       ['10', '11', '12', '13', '14', '15', '16', '17', '18', '19']],
      dtype='<U11')

In [44]:
 np.fromiter(range(10),dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [46]:
np.add.reduce(a)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [47]:
 np.array_equal(a,b)

False

In [48]:
np.allclose(1,1)

True

In [49]:
np.arctan2(10,24)

0.3947911196997615

In [50]:
a.argmax()

19

In [51]:
a.view(np.int16)

array([[ 0,  0,  1,  0,  2,  0,  3,  0,  4,  0,  5,  0,  6,  0,  7,  0,
         8,  0,  9,  0],
       [10,  0, 11,  0, 12,  0, 13,  0, 14,  0, 15,  0, 16,  0, 17,  0,
        18,  0, 19,  0]], dtype=int16)